### PR TITLE
[FSTORE-495] Cytibike Tutorial

### PR DESCRIPTION
**Pull request by rktraz**

### CODE REVIEW

**Comment by Maxxx-zh** [comment]
Update all buttons links:

button_before

`[Open In Colab](https://colab.research.google.com/github/logicalclocks/hopsworks-tutorials/blob/master/advanced_tutorials/{project_name}/{notebook_name}.ipynb)`

**Comment by Maxxx-zh** [comment]
Replace commas with dots in.

remove_dots1

**Comment by Maxxx-zh** [comment]
Delete import line and add it to **imports section.**

replace import

imports_section

**Comment by Maxxx-zh** [comment]
1_backfill_feature_groups: Dead FG link

dead_page1
dead_page2

**Comment by Maxxx-zh** [comment]
Add a name of API_KEY so user can copy it instead of typing manually.

`VISUALCROSSING_API_KEY = 'YOUR_API_KEY'`

before
after

**Comment by Maxxx-zh** [comment]
Streamlit_app.py:

Add **default station** in order not to see an empty map:

empty_map

https://docs.streamlit.io/library/api-reference/widgets/st.multiselect
docs

**Comment by Maxxx-zh** [comment]
Some eye catching warnings are present ⬇️

warnings

**Review by davitbzh — APPROVED** [review]

**Pull request merged**
