### PR TITLE
Credit scores project

### PR DESCRIPTION
**Pull request by Maxxx-zh**

### CODE REVIEW

**Comment by rktraz** [comment]
image

In all notebooks please fix the headers:

1. make the fonts bold, like in my PR
2. fix the "sections number"

**Comment by rktraz** [comment]
image
in 1st notebook - there is no such datafile in folder

**Comment by rktraz** [comment]
Also we have to agree on how the README.md files should look like
Should they all be strictly the same format etc
Also question to @davitbzh

**Comment by rktraz** [comment]
image
Davit told me to avoid writing constructions like

1. "Loading batch data." (instead, write "How to load batch data / Simply load batch data",
2.  "In this notebook we will see how" - "In this notebook **you will** ..."

**Comment by rktraz** [comment]
image
Let's place all cells with get_or_create_feature_group not in the separate section, but inside "🔮 Connecting to Hopsworks Feature Store"

**Comment by rktraz** [comment]
image
Look how I did

**Comment by rktraz** [comment]
Please rename all feature groups:
instead of "installments_payments**_fg**" -> "installments_payments", etc

**Review by davitbzh — APPROVED** [review]

**Pull request merged**
